import {
  DisputeRecord,
  CustomerProfileData,
  OrderDetailData,
  EvidenceItem,
  AuditLogRecord,
  NotificationItem,
  IntegrationRecord,
  OrganizationInfo,
} from '@/lib/types';

export const mockOrganizations: OrganizationInfo[] = [
  {
    id: 'org-1',
    name: 'Acme SaaS Corp',
    slug: 'acme-saas',
    plan: 'Enterprise Scale',
    timezone: 'America/New_York (EST)',
    currency: 'USD',
    autoPilotEnabled: true,
    autoPilotThreshold: 85,
    defaultRebuttalTone: 'firm',
    slaWarningHours: 48,
  },
  {
    id: 'org-2',
    name: 'Apex Global Retail',
    slug: 'apex-retail',
    plan: 'Growth',
    timezone: 'America/Los_Angeles (PST)',
    currency: 'USD',
    autoPilotEnabled: false,
    autoPilotThreshold: 90,
    defaultRebuttalTone: 'detailed',
    slaWarningHours: 24,
  },
  {
    id: 'org-3',
    name: 'CloudScale Technologies',
    slug: 'cloudscale-tech',
    plan: 'Fintech Pro',
    timezone: 'Europe/London (GMT)',
    currency: 'USD',
    autoPilotEnabled: true,
    autoPilotThreshold: 80,
    defaultRebuttalTone: 'concise',
    slaWarningHours: 36,
  },
];

export const mockCustomers: CustomerProfileData[] = [
  {
    id: 'cust-101',
    organizationId: 'org-1',
    email: 'marcus.vance@techcorp.io',
    name: 'Marcus Vance',
    phoneNumber: '+1 (415) 890-2134',
    address: '742 Evergreen Terrace, Springfield, OR 97477',
    totalOrdersCount: 8,
    lifetimeValue: 3840.0,
    previousDisputesCount: 0,
    previousDisputesWon: 0,
    fraudRiskScore: 12,
    accountCreatedAt: '2025-01-14T09:30:00Z',
    lastLoginAt: '2026-08-24T18:12:00Z',
    hasAcceptedTos: true,
    tosAcceptedAt: '2025-01-14T09:32:15Z',
    tosVersion: 'v2024.4_enterprise',
    sessionLogs: [
      {
        id: 'sess-1',
        ipAddress: '198.51.100.45',
        location: 'Springfield, OR, United States',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/128.0',
        timestamp: '2026-08-24T18:12:00Z',
        action: 'Dashboard Login & API Key Rotation',
        deviceFingerprint: 'dfp_a982fbc091',
      },
      {
        id: 'sess-2',
        ipAddress: '198.51.100.45',
        location: 'Springfield, OR, United States',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/128.0',
        timestamp: '2026-08-10T14:22:00Z',
        action: 'Order Placed #ORD-8821',
        deviceFingerprint: 'dfp_a982fbc091',
      },
      {
        id: 'sess-3',
        ipAddress: '198.51.100.45',
        location: 'Springfield, OR, United States',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/128.0',
        timestamp: '2026-08-14T11:05:00Z',
        action: 'Downloaded Invoice #INV-8821',
        deviceFingerprint: 'dfp_a982fbc091',
      },
    ],
  },
  {
    id: 'cust-102',
    organizationId: 'org-1',
    email: 'sarah.jenkins@designcraft.co',
    name: 'Sarah Jenkins',
    phoneNumber: '+1 (212) 555-0199',
    address: '350 5th Avenue, Suite 4800, New York, NY 10118',
    totalOrdersCount: 4,
    lifetimeValue: 5196.0,
    previousDisputesCount: 1,
    previousDisputesWon: 1,
    fraudRiskScore: 18,
    accountCreatedAt: '2025-06-20T11:00:00Z',
    lastLoginAt: '2026-08-23T21:40:00Z',
    hasAcceptedTos: true,
    tosAcceptedAt: '2025-06-20T11:04:30Z',
    tosVersion: 'v2025.1_saas',
    sessionLogs: [
      {
        id: 'sess-4',
        ipAddress: '203.0.113.88',
        location: 'New York, NY, United States',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/127.0.0.0 Safari/537.36',
        timestamp: '2026-08-23T21:40:00Z',
        action: 'Active Workspace Session',
        deviceFingerprint: 'dfp_c441aa9082',
      },
      {
        id: 'sess-5',
        ipAddress: '203.0.113.88',
        location: 'New York, NY, United States',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/127.0.0.0 Safari/537.36',
        timestamp: '2026-08-01T08:15:00Z',
        action: 'Annual Plan Subscription Renewed',
        deviceFingerprint: 'dfp_c441aa9082',
      },
    ],
  },
  {
    id: 'cust-103',
    organizationId: 'org-1',
    email: 'alex.rivera@hypergrowth.net',
    name: 'Alex Rivera',
    phoneNumber: '+1 (312) 555-8765',
    address: '233 S Wacker Dr, Floor 32, Chicago, IL 60606',
    totalOrdersCount: 2,
    lifetimeValue: 178.0,
    previousDisputesCount: 0,
    previousDisputesWon: 0,
    fraudRiskScore: 35,
    accountCreatedAt: '2026-06-15T14:10:00Z',
    lastLoginAt: '2026-08-18T10:05:00Z',
    hasAcceptedTos: true,
    tosAcceptedAt: '2026-06-15T14:12:00Z',
    tosVersion: 'v2026.1_standard',
    sessionLogs: [
      {
        id: 'sess-6',
        ipAddress: '192.0.2.14',
        location: 'Chicago, IL, United States',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15',
        timestamp: '2026-08-18T10:05:00Z',
        action: 'Exported 14 Reports',
        deviceFingerprint: 'dfp_iphone_908',
      },
    ],
  },
];

export const mockOrders: OrderDetailData[] = [
  {
    id: 'ord-8821',
    organizationId: 'org-1',
    customerId: 'cust-101',
    externalOrderId: 'ORD-8821-EXP',
    amount: 420.0,
    currency: 'USD',
    status: 'completed',
    items: [
      {
        name: 'Enterprise Hardware Security Key Bundle (x4)',
        sku: 'HW-SEC-4X',
        quantity: 1,
        price: 420.0,
        type: 'physical',
      },
    ],
    billingAddress: '742 Evergreen Terrace, Springfield, OR 97477',
    shippingAddress: '742 Evergreen Terrace, Springfield, OR 97477',
    avsResult: 'MATCH',
    cvcResult: 'MATCH',
    threeDSecure: 'AUTHENTICATED',
    trackingNumber: 'FX-9821739812US',
    carrier: 'FedEx Priority Overnight',
    carrierStatus: 'DELIVERED',
    deliverySignature: 'M. Vance (Direct Signature)',
    shippedAt: '2026-08-11T16:00:00Z',
    deliveredAt: '2026-08-12T10:24:00Z',
    createdAt: '2026-08-10T14:22:00Z',
  },
  {
    id: 'ord-7193',
    organizationId: 'org-1',
    customerId: 'cust-102',
    externalOrderId: 'ORD-7193-SAAS',
    amount: 1299.0,
    currency: 'USD',
    status: 'completed',
    items: [
      {
        name: 'Chargeback Defender Enterprise Yearly Seat Plan',
        sku: 'PLAN-ENT-YEAR',
        quantity: 1,
        price: 1299.0,
        type: 'subscription',
      },
    ],
    billingAddress: '350 5th Avenue, Suite 4800, New York, NY 10118',
    shippingAddress: '350 5th Avenue, Suite 4800, New York, NY 10118',
    avsResult: 'MATCH',
    cvcResult: 'MATCH',
    threeDSecure: 'AUTHENTICATED',
    createdAt: '2026-08-01T08:15:00Z',
  },
  {
    id: 'ord-6420',
    organizationId: 'org-1',
    customerId: 'cust-103',
    externalOrderId: 'ORD-6420-SUB',
    amount: 89.0,
    currency: 'USD',
    status: 'completed',
    items: [
      {
        name: 'Professional Tier Recurring Cloud License (Monthly)',
        sku: 'PLAN-PRO-MO',
        quantity: 1,
        price: 89.0,
        type: 'subscription',
      },
    ],
    billingAddress: '233 S Wacker Dr, Floor 32, Chicago, IL 60606',
    avsResult: 'MATCH',
    cvcResult: 'MATCH',
    threeDSecure: 'AUTHENTICATED',
    createdAt: '2026-07-20T00:00:00Z',
  },
];

export const mockEvidenceItems: EvidenceItem[] = [
  {
    id: 'ev-101',
    disputeId: 'dsp-8821',
    type: 'SHIPPING_PROOF',
    title: 'FedEx Direct Signature & GPS Delivery Certificate',
    content:
      'FedEx Tracking #FX-9821739812US delivered on August 12, 2026 at 10:24 AM. Signed by "M. Vance". GPS coordinates 44.0462° N, 123.0220° W match registered cardholder delivery address.',
    fileUrl: '/evidence/fedex_signature_8821.pdf',
    fileSize: '420 KB',
    fileType: 'PDF Document',
    sourceIntegration: 'FedEx Webhook Sync',
    isAutoCollected: true,
    confidenceScore: 98,
    isIncludedInSubmission: true,
    verifiedAt: '2026-08-24T08:00:00Z',
    createdAt: '2026-08-24T08:00:00Z',
  },
  {
    id: 'ev-102',
    disputeId: 'dsp-8821',
    type: 'ORDER_DETAILS',
    title: 'Stripe 3D-Secure 2.2 Full Authentication Receipt',
    content:
      '3DS Challenge successfully completed by cardholder via SMS OTP on Chase Visa ****4291. Full liability shift applies under Visa Rule 10.4.',
    fileUrl: '/evidence/stripe_3ds_log_8821.json',
    fileSize: '45 KB',
    fileType: 'JSON Security Log',
    sourceIntegration: 'Stripe API',
    isAutoCollected: true,
    confidenceScore: 99,
    isIncludedInSubmission: true,
    verifiedAt: '2026-08-24T08:00:00Z',
    createdAt: '2026-08-24T08:00:00Z',
  },
  {
    id: 'ev-103',
    disputeId: 'dsp-8821',
    type: 'ACTIVITY_LOGS',
    title: 'Customer SaaS Portal Session & IP Geolocation Match',
    content:
      'Customer authenticated into portal from IP 198.51.100.45 (ISP: Comcast Cable / Springfield OR) on August 14, 2026 and downloaded invoice #INV-8821 two days after delivery.',
    fileUrl: '/evidence/session_audit_8821.log',
    fileSize: '18 KB',
    fileType: 'Text Audit Log',
    sourceIntegration: 'Session Telemetry Hub',
    isAutoCollected: true,
    confidenceScore: 94,
    isIncludedInSubmission: true,
    verifiedAt: '2026-08-24T08:05:00Z',
    createdAt: '2026-08-24T08:05:00Z',
  },
  {
    id: 'ev-104',
    disputeId: 'dsp-8821',
    type: 'TOS_AGREEMENT',
    title: 'Signed Master Terms & Non-Refundable Hardware Clause',
    content:
      'Explicit checkbox "I agree to the Hardware Delivery & Return Policy" accepted at timestamp 2026-08-10T14:22:00Z with cardholder IP logged.',
    fileUrl: '/evidence/tos_signature_8821.pdf',
    fileSize: '1.2 MB',
    fileType: 'PDF Agreement',
    sourceIntegration: 'Shopify Checkout API',
    isAutoCollected: true,
    confidenceScore: 92,
    isIncludedInSubmission: true,
    verifiedAt: '2026-08-24T08:05:00Z',
    createdAt: '2026-08-24T08:05:00Z',
  },
  {
    id: 'ev-201',
    disputeId: 'dsp-7193',
    type: 'CUSTOMER_COMMUNICATION',
    title: 'Zendesk Support Ticket #ZD-4920 Onboarding Thread',
    content:
      'Sarah Jenkins exchanged 6 messages with Customer Success Lead regarding API key provisioning for their team. Confirms active receipt and usage of software services.',
    fileUrl: '/evidence/zendesk_ticket_4920.pdf',
    fileSize: '310 KB',
    fileType: 'Support Transcript',
    sourceIntegration: 'Zendesk CRM Connector',
    isAutoCollected: true,
    confidenceScore: 96,
    isIncludedInSubmission: true,
    verifiedAt: '2026-08-23T14:00:00Z',
    createdAt: '2026-08-23T14:00:00Z',
  },
  {
    id: 'ev-202',
    disputeId: 'dsp-7193',
    type: 'ACTIVITY_LOGS',
    title: 'Cloud Workspace Telemetry (45 Active Team Logins)',
    content:
      '45 separate user sessions recorded in the billed period with 1,240 API requests executed across team workspace.',
    fileUrl: '/evidence/telemetry_7193.csv',
    fileSize: '85 KB',
    fileType: 'CSV Telemetry',
    sourceIntegration: 'CloudScale Telemetry',
    isAutoCollected: true,
    confidenceScore: 95,
    isIncludedInSubmission: true,
    verifiedAt: '2026-08-23T14:05:00Z',
    createdAt: '2026-08-23T14:05:00Z',
  },
  {
    id: 'ev-301',
    disputeId: 'dsp-6420',
    type: 'REFUND_POLICY',
    title: 'Explicit Subscription Auto-Renewal Disclosure & Invoicing',
    content:
      'Renewal reminder email sent 7 days prior to billing on July 13, 2026. Email opened by customer at 10:14 AM.',
    fileUrl: '/evidence/renewal_email_6420.eml',
    fileSize: '55 KB',
    fileType: 'Email Record',
    sourceIntegration: 'Postmark Email API',
    isAutoCollected: true,
    confidenceScore: 90,
    isIncludedInSubmission: true,
    verifiedAt: '2026-08-22T09:00:00Z',
    createdAt: '2026-08-22T09:00:00Z',
  },
];

export const mockDisputes: DisputeRecord[] = [
  {
    id: 'dsp-8821',
    organizationId: 'org-1',
    orderId: 'ord-8821',
    customerId: 'cust-101',
    externalDisputeId: 'dp_1Q82x98K928198A',
    processor: 'stripe',
    processorDisputeId: 'dp_1Q82x98K928198A',
    reason: 'Product not received',
    reasonCode: '10.4',
    amount: 420.0,
    feeAmount: 15.0,
    currency: 'USD',
    status: 'PENDING_APPROVAL',
    deadline: new Date(Date.now() + 28 * 3600 * 1000).toISOString(), // ~28 hours left
    riskLevel: 'LOW',
    cardBrand: 'visa',
    cardLast4: '4291',
    cardholderName: 'Marcus Vance',
    evidenceStrengthScore: 96,
    winProbability: 92,
    rebuttalTone: 'firm',
    rebuttalLetter: `FORMAL DISPUTE REBUTTAL — VISA REASON CODE 10.4 (MERCHANDISE NOT RECEIVED)

To: Visa Dispute Resolution & Acquiring Bank Review Team
Merchant: Acme SaaS Corp / Chargeback Defender Enterprise
Case Reference: dp_1Q82x98K928198A | Order Reference: ORD-8821-EXP
Disputed Amount: $420.00 USD | Cardholder: Marcus Vance (Visa ending in 4291)

EXECUTIVE SUMMARY:
The cardholder filed a dispute claiming "Product Not Received" for an enterprise physical security hardware key bundle ($420.00). We categorically demonstrate that the merchandise was purchased using 3D-Secure 2.2 authentication, dispatched via FedEx Priority Overnight, and successfully delivered with the cardholder's direct physical signature and matching GPS coordinates. Furthermore, the cardholder accessed our digital customer portal to view the invoice following delivery.

EVIDENCE BREAKDOWN:
1. Proof of Delivery (Exhibit A):
   - Carrier: FedEx Express Tracking #FX-9821739812US
   - Delivery Date & Time: August 12, 2026 at 10:24 AM
   - Physical Signature: "M. Vance" on delivery receipt
   - GPS Verification: Delivered at 44.0462° N, 123.0220° W (Springfield, OR), exactly matching the verified cardholder billing and shipping address.

2. 3D-Secure 2.2 & Identity Verification (Exhibit B):
   - Transaction was fully authenticated using 3DS OTP verified by Chase Bank.
   - Under Visa Core Rules (Liability Shift for 3DS Transactions), the merchant has satisfied all authentication standards.

3. Subsequent Merchant Engagement (Exhibit C):
   - On August 14, 2026, the cardholder authenticated into their account from IP 198.51.100.45 and downloaded the delivery invoice.

CONCLUSION & REQUEST:
In accordance with Visa Operating Regulations for Compelling Evidence (Rule 10.4), the merchant has provided irrefutable proof of physical delivery to the cardholder address with signature confirmation. We respectfully request that this dispute be decided in the merchant's favor and the funds immediately credited back.`,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    aiAnalysis: {
      overallStrengthScore: 96,
      winProbabilityPercent: 92,
      recommendedAction: 'SUBMIT_DEFENSE',
      reasonClassification: 'Physical Delivery Dispute with Strong Carrier Signature & 3DS',
      applicableCompellingEvidenceRule: 'Visa CE 3.0 Qualified (Proof of Delivery to Verified Cardholder Address + 3DS OTP)',
      strengths: [
        'Direct signature match ("M. Vance") on FedEx delivery manifest',
        '3DS 2.2 cryptographic liability shift on Chase Visa card',
        'Post-delivery portal login and invoice download from matching IP address',
        'Cardholder AVS & CVC matched with 100% precision at checkout',
      ],
      vulnerabilities: [],
      missingEvidenceRecommendations: [
        {
          title: 'Warehouse serial number barcode log',
          impact: 'LOW',
          reason: 'Provides additional redundancy if carrier signature is challenged',
        },
      ],
      suggestedRebuttalLetter: '',
      contradictionFlags: [],
    },
  },
  {
    id: 'dsp-7193',
    organizationId: 'org-1',
    orderId: 'ord-7193',
    customerId: 'cust-102',
    externalDisputeId: 'ch_3M92830182937402',
    processor: 'shopify',
    processorDisputeId: 'sh_dsp_99214',
    reason: 'Fraudulent / Cardholder Unrecognized',
    reasonCode: '4837',
    amount: 1299.0,
    feeAmount: 15.0,
    currency: 'USD',
    status: 'OPEN',
    deadline: new Date(Date.now() + 110 * 3600 * 1000).toISOString(),
    riskLevel: 'MEDIUM',
    cardBrand: 'mastercard',
    cardLast4: '8810',
    cardholderName: 'Sarah Jenkins',
    evidenceStrengthScore: 89,
    winProbability: 86,
    rebuttalTone: 'firm',
    rebuttalLetter: `FORMAL DISPUTE REBUTTAL — MASTERCARD REASON CODE 4837 (NO CARDHOLDER AUTHORIZATION)

Merchant: Acme SaaS Corp | Order: ORD-7193-SAAS
Disputed Amount: $1,299.00 USD | Cardholder: Sarah Jenkins

We demonstrate active authorized usage of the purchased enterprise software license by the named cardholder and her organization. The cardholder engaged with our support team via verified corporate email and completed 45 team logins across the billed annual period.`,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    aiAnalysis: {
      overallStrengthScore: 89,
      winProbabilityPercent: 86,
      recommendedAction: 'SUBMIT_DEFENSE',
      reasonClassification: 'Authorized SaaS Subscription Disputed as Fraud',
      applicableCompellingEvidenceRule: 'Mastercard Compelling Evidence 2.0 (Active SaaS Telemetry + Corporate Email Support)',
      strengths: [
        'Zendesk conversation with cardholder detailing onboarding and API keys',
        '45 active SaaS logins originating from cardholder corporate IP range',
        '3DS authentication verified at checkout',
      ],
      vulnerabilities: [
        'Cardholder did not sign an offline enterprise MSA document (click-wrap terms only)',
      ],
      missingEvidenceRecommendations: [
        {
          title: 'Export full user login IP log CSV',
          impact: 'MEDIUM',
          reason: 'Confirms continuous utility and authorization across billing period',
        },
      ],
      suggestedRebuttalLetter: '',
      contradictionFlags: [],
    },
  },
  {
    id: 'dsp-6420',
    organizationId: 'org-1',
    orderId: 'ord-6420',
    customerId: 'cust-103',
    externalDisputeId: 'PP-D-9982711',
    processor: 'paypal',
    processorDisputeId: 'PP-D-9982711',
    reason: 'Subscription Canceled Prior to Charge',
    reasonCode: 'recurring_canceled',
    amount: 89.0,
    feeAmount: 20.0,
    currency: 'USD',
    status: 'EVIDENCE_COLLECTING',
    deadline: new Date(Date.now() + 68 * 3600 * 1000).toISOString(),
    riskLevel: 'LOW',
    cardBrand: 'amex',
    cardLast4: '1004',
    cardholderName: 'Alex Rivera',
    evidenceStrengthScore: 78,
    winProbability: 74,
    rebuttalTone: 'concise',
    rebuttalLetter: `To: PayPal Dispute Resolution Team
Merchant: Acme SaaS Corp

The customer claims their subscription was canceled prior to billing. Our audit logs show the cancellation request was executed on July 23, 2026, three days AFTER the scheduled renewal on July 20. In addition, the customer exported 14 reports on August 18.`,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'dsp-5912',
    organizationId: 'org-1',
    orderId: 'ord-8821',
    customerId: 'cust-101',
    externalDisputeId: 'adyen_dsp_88192',
    processor: 'adyen',
    processorDisputeId: 'adyen_dsp_88192',
    reason: 'Product Not As Described',
    reasonCode: '4853',
    amount: 650.0,
    feeAmount: 15.0,
    currency: 'USD',
    status: 'SUBMITTED',
    deadline: new Date(Date.now() + 190 * 3600 * 1000).toISOString(),
    riskLevel: 'MEDIUM',
    cardBrand: 'visa',
    cardLast4: '4291',
    cardholderName: 'Marcus Vance',
    evidenceStrengthScore: 88,
    winProbability: 84,
    rebuttalTone: 'detailed',
    rebuttalLetter: `Submitted defense package with technical specifications and customer signed acceptance sign-off.`,
    submittedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    approvedByUserId: 'user-1',
    approvedByUserName: 'Admin User (Risk Lead)',
    approvalNotes: 'All product specifications and delivery sign-offs attached.',
    approvedAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'dsp-4310',
    organizationId: 'org-1',
    orderId: 'ord-7193',
    customerId: 'cust-102',
    externalDisputeId: 'dp_1WonCase9901',
    processor: 'stripe',
    processorDisputeId: 'dp_1WonCase9901',
    reason: 'Fraudulent Transaction',
    reasonCode: '10.4',
    amount: 149.99,
    feeAmount: 15.0,
    currency: 'USD',
    status: 'WON',
    deadline: new Date(Date.now() - 10 * 86400000).toISOString(),
    riskLevel: 'LOW',
    cardBrand: 'visa',
    cardLast4: '8810',
    cardholderName: 'Sarah Jenkins',
    evidenceStrengthScore: 98,
    winProbability: 95,
    rebuttalTone: 'firm',
    rebuttalLetter: 'Visa CE 3.0 Compelling evidence submitted. Cardholder confirmed 2 prior undisputed transactions.',
    submittedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    resolvedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'dsp-3890',
    organizationId: 'org-1',
    orderId: 'ord-8821',
    customerId: 'cust-101',
    externalDisputeId: 'bt_dispute_44109',
    processor: 'braintree',
    processorDisputeId: 'bt_dispute_44109',
    reason: 'Duplicate Charge',
    reasonCode: 'duplicate_processing',
    amount: 29.0,
    feeAmount: 15.0,
    currency: 'USD',
    status: 'WON',
    deadline: new Date(Date.now() - 18 * 86400000).toISOString(),
    riskLevel: 'LOW',
    cardBrand: 'mastercard',
    cardLast4: '4291',
    cardholderName: 'Marcus Vance',
    evidenceStrengthScore: 92,
    winProbability: 90,
    rebuttalTone: 'concise',
    rebuttalLetter: 'Rebuttal proved two distinct shipments with unique carrier tracking numbers.',
    resolvedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'dsp-2144',
    organizationId: 'org-1',
    orderId: 'ord-6420',
    customerId: 'cust-103',
    externalDisputeId: 'sq_dsp_00291',
    processor: 'square',
    processorDisputeId: 'sq_dsp_00291',
    reason: 'Credit Not Processed',
    reasonCode: 'credit_not_given',
    amount: 350.0,
    feeAmount: 15.0,
    currency: 'USD',
    status: 'LOST',
    deadline: new Date(Date.now() - 30 * 86400000).toISOString(),
    riskLevel: 'HIGH',
    cardBrand: 'discover',
    cardLast4: '9901',
    cardholderName: 'Alex Rivera',
    evidenceStrengthScore: 42,
    winProbability: 35,
    rebuttalTone: 'detailed',
    rebuttalLetter: 'Insufficient return proof at warehouse inspection.',
    resolvedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'dsp-9014',
    organizationId: 'org-1',
    orderId: 'ord-8821',
    customerId: 'cust-101',
    externalDisputeId: 'dp_1URGENT_DEADLINE',
    processor: 'stripe',
    processorDisputeId: 'dp_1URGENT_DEADLINE',
    reason: 'Unrecognized Transaction / Fraud',
    reasonCode: '10.4',
    amount: 850.0,
    feeAmount: 15.0,
    currency: 'USD',
    status: 'PENDING_APPROVAL',
    deadline: new Date(Date.now() + 16 * 3600 * 1000).toISOString(), // 16 hours left!
    riskLevel: 'CRITICAL',
    cardBrand: 'visa',
    cardLast4: '4291',
    cardholderName: 'Marcus Vance',
    evidenceStrengthScore: 93,
    winProbability: 88,
    rebuttalTone: 'firm',
    rebuttalLetter: `URGENT VISA CHARGEBACK DEFENSE — EVIDENCE OF PREVIOUS TRANSACTION RELATIONSHIP (VISA CE 3.0)

Cardholder Marcus Vance claims unrecognized charge for enterprise hardware bundle. Merchant provides 2 historical undisputed purchases with identical card fingerprint, billing address, and phone number.`,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    aiAnalysis: {
      overallStrengthScore: 93,
      winProbabilityPercent: 88,
      recommendedAction: 'SUBMIT_DEFENSE',
      reasonClassification: 'Visa CE 3.0 Eligible Fraud Dispute',
      applicableCompellingEvidenceRule: 'Visa CE 3.0 (Two Prior Undisputed Orders with Matching IP & Delivery Address)',
      strengths: [
        'Matches 2 prior undisputed orders from same customer account',
        'Direct IP geolocation match with cardholder registered office',
        'Signed terms of service with non-repudiation log',
      ],
      vulnerabilities: [
        'Deadline expires in under 18 hours — Immediate human sign-off required',
      ],
      missingEvidenceRecommendations: [],
      suggestedRebuttalLetter: '',
      contradictionFlags: [],
    },
  },
];

export const mockAuditLogs: AuditLogRecord[] = [
  {
    id: 'aud-1',
    organizationId: 'org-1',
    userId: 'user-1',
    userName: 'Elena Rostova (Risk Manager)',
    userRole: 'RISK_MANAGER',
    action: 'DISPUTE_AI_ANALYSIS_GENERATED',
    entityType: 'DISPUTE',
    entityId: 'dsp-8821',
    details: 'AI Engine evaluated evidence strength at 96% with Visa CE 3.0 qualification.',
    ipAddress: '172.56.21.9',
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'aud-2',
    organizationId: 'org-1',
    userId: 'user-1',
    userName: 'Elena Rostova (Risk Manager)',
    userRole: 'RISK_MANAGER',
    action: 'EVIDENCE_AUTO_COLLECTED',
    entityType: 'EVIDENCE',
    entityId: 'dsp-8821',
    details: 'Auto-ingested FedEx delivery proof #FX-9821739812US and Stripe 3DS auth logs.',
    ipAddress: '172.56.21.9',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'aud-3',
    organizationId: 'org-1',
    userId: 'user-2',
    userName: 'David Miller (Lead Analyst)',
    userRole: 'DISPUTE_ANALYST',
    action: 'REBUTTAL_TONE_UPDATED',
    entityType: 'DISPUTE',
    entityId: 'dsp-8821',
    details: 'Updated rebuttal tone to "Firm Legal" and verified CE 3.0 clause wording.',
    ipAddress: '198.51.100.12',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'aud-4',
    organizationId: 'org-1',
    userId: 'user-1',
    userName: 'Elena Rostova (Risk Manager)',
    userRole: 'RISK_MANAGER',
    action: 'DISPUTE_SUBMITTED_TO_PROCESSOR',
    entityType: 'DISPUTE',
    entityId: 'dsp-5912',
    details: 'Signed off and submitted $650.00 dispute package to Adyen Acquiring Network.',
    ipAddress: '172.56.21.9',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'aud-5',
    organizationId: 'org-1',
    userName: 'Webhook Ingestion Worker',
    userRole: 'SYSTEM_BOT',
    action: 'INTEGRATION_WEBHOOK_RECEIVED',
    entityType: 'INTEGRATION',
    entityId: 'int-stripe',
    details: 'Ingested chargeback notice for dp_1URGENT_DEADLINE ($850.00) via Stripe webhook.',
    ipAddress: '54.187.12.89',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    organizationId: 'org-1',
    title: 'Urgent Deadline Warning (< 18 Hours)',
    message: 'Dispute dp_1URGENT_DEADLINE ($850.00) requires sign-off before 11:59 PM tonight.',
    type: 'DEADLINE_URGENT',
    severity: 'critical',
    read: false,
    linkUrl: '/disputes/dsp-9014',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    organizationId: 'org-1',
    title: 'Dispute Won! +$149.99 Recovered',
    message: 'Stripe resolved dp_1WonCase9901 in your favor under Visa CE 3.0 rule.',
    type: 'DISPUTE_WON',
    severity: 'success',
    read: false,
    linkUrl: '/disputes/dsp-4310',
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    organizationId: 'org-1',
    title: 'Evidence Package Ready for Approval',
    message: 'AI generated 96% confidence rebuttal for Marcus Vance ($420.00). Awaiting human review.',
    type: 'APPROVAL_NEEDED',
    severity: 'warning',
    read: false,
    linkUrl: '/disputes/dsp-8821',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-4',
    organizationId: 'org-1',
    title: 'New Chargeback Ingested from Shopify',
    message: 'Dispute ch_3M92830182937402 ($1,299.00) imported and matched to Customer #102.',
    type: 'DISPUTE_NEW',
    severity: 'info',
    read: true,
    linkUrl: '/disputes/dsp-7193',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
];

export const mockIntegrations: IntegrationRecord[] = [
  {
    id: 'int-stripe',
    organizationId: 'org-1',
    processor: 'stripe',
    displayName: 'Stripe Direct Payments',
    category: 'PAYMENT_PROCESSOR',
    status: 'connected',
    lastSyncAt: '2 mins ago',
    syncedDisputesCount: 142,
    webhookUrl: 'https://api.chargebackdefender.io/v1/webhooks/stripe_live_prod',
    apiKeyMasked: 'rk_live_••••••••••••9481',
    config: {
      autoSyncDisputes: true,
      syncIntervalMinutes: 5,
      earlyFraudWarning: true,
      verifiIntegration: true,
    },
  },
  {
    id: 'int-shopify',
    organizationId: 'org-1',
    processor: 'shopify',
    displayName: 'Shopify Payments & Store Orders',
    category: 'ECOMMERCE',
    status: 'connected',
    lastSyncAt: '12 mins ago',
    syncedDisputesCount: 68,
    webhookUrl: 'https://api.chargebackdefender.io/v1/webhooks/shopify_app_live',
    apiKeyMasked: 'shpat_••••••••••••8819',
    config: {
      autoPullFulfillments: true,
      pullCustomerNotes: true,
    },
  },
  {
    id: 'int-paypal',
    organizationId: 'org-1',
    processor: 'paypal',
    displayName: 'PayPal Business Dispute Manager',
    category: 'PAYMENT_PROCESSOR',
    status: 'connected',
    lastSyncAt: '35 mins ago',
    syncedDisputesCount: 29,
    webhookUrl: 'https://api.chargebackdefender.io/v1/webhooks/paypal_ipn_live',
    apiKeyMasked: 'client_••••••••••••3310',
    config: {
      disputeApiVersion: 'v2',
      sandboxMode: false,
    },
  },
  {
    id: 'int-fedex',
    organizationId: 'org-1',
    processor: 'fedex',
    displayName: 'FedEx Web Services & Signature Scans',
    category: 'SHIPPING',
    status: 'connected',
    lastSyncAt: 'Just now',
    syncedDisputesCount: 215,
    webhookUrl: 'https://api.chargebackdefender.io/v1/webhooks/fedex_tracking',
    apiKeyMasked: 'fdx_••••••••••••0091',
    config: {
      fetchSignatureProofImages: true,
      fetchGpsDeliveryCoordinates: true,
    },
  },
  {
    id: 'int-zendesk',
    organizationId: 'org-1',
    processor: 'zendesk',
    displayName: 'Zendesk Support CRM & Chat Transcripts',
    category: 'CRM_SUPPORT',
    status: 'connected',
    lastSyncAt: '1 hour ago',
    syncedDisputesCount: 84,
    webhookUrl: 'https://api.chargebackdefender.io/v1/webhooks/zendesk_sync',
    apiKeyMasked: 'zd_token_••••••••••••7721',
    config: {
      indexCustomerTickets: true,
      includeClosedTickets: true,
    },
  },
  {
    id: 'int-ethoca',
    organizationId: 'org-1',
    processor: 'ethoca',
    displayName: 'Ethoca / Mastercard Consumer Clarity',
    category: 'ALERT_NETWORK',
    status: 'connected',
    lastSyncAt: '4 hours ago',
    syncedDisputesCount: 19,
    webhookUrl: 'https://api.chargebackdefender.io/v1/webhooks/ethoca_clarity',
    apiKeyMasked: 'eth_••••••••••••1029',
    config: {
      autoRefundOnMatch: false,
      alertNotificationEmail: 'risk-team@acme.com',
    },
  },
  {
    id: 'int-verifi',
    organizationId: 'org-1',
    processor: 'verifi',
    displayName: 'Verifi CDRN & Visa Order Insight (CE 3.0)',
    category: 'ALERT_NETWORK',
    status: 'connected',
    lastSyncAt: '18 mins ago',
    syncedDisputesCount: 37,
    webhookUrl: 'https://api.chargebackdefender.io/v1/webhooks/verifi_cdrn',
    apiKeyMasked: 'vrf_••••••••••••4902',
    config: {
      enableVisaOrderInsight: true,
      visaCE3AutomatedFiling: true,
    },
  },
];
